project:
  type: website
  output-dir: docs

website:
  title: "Matplotlib.Gridspec"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: J089_Lab1_Numpy-checkpoint.ipynb
        text: Assignment 


format:
  html:
    theme:
      light: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto