project:
  type: website
  output-dir: docs

website:
  title: "Matplotlib.Gridspec"
  content: "matplotlib_gridspec_with_installation 3.ipynb"
  navbar:
    left:
      - href: matplotlib_gridspec_with_installation 3.ipynb
        text: HOME
      - href: matplotlib_gridspec_key_features 4.ipynb
        text: Key Features
      - href: gridspec_use_cases 5.ipynb
        text: Use Cases 
  page-footer:
    center: "© J089"


format:
  html:
    theme:
      light: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto