project:
  type: website
  output-dir: docs

website:
  title: "Matplotlib.Gridspec"
  navbar:
    left:
      - href: matplotlib_gridspec_with_installation 3.ipynb
        text: HOME
      - href: key_features_with_parameters.ipynb
        text: Key Features|Parameters
      - href: gridspec_use_cases 5.ipynb
        text: Use Cases 
      - href: gridspec_conclusion_references 6.ipynb
        text: Conclusion|References
      - href: conclusion_acknowledgment 7.ipynb
        text: Takeaways
  page-footer:
    center: "© J089"


format:
  html:
    theme:
      light: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto